<a href="https://colab.research.google.com/github/victoriairungu99-creator/CDAV-course/blob/main/Copy_of_Week_3_Day_12(Tuesday).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectorization

Allows you to generate a lot of output without looping as looping is time consuming and tiring with a huge dataset

In [ ]:
import numpy as np #include np.array so as to allow vectorization
scores=[45,89,76,67]
scores= np.array(scores)
scores+5

array([50, 94, 81, 72])

In [ ]:
#numpy can also be used to add different lists and give totals on each indexe(i.e, for each student)
#this one is for adding lists and it gives you the numbers in  total as they are but not added
end_term_scores=[90,79,67,45]
mid_term_scores=[43,78,42,89]
cat_scores=[95,82,93,79]
end_term_scores+mid_term_scores+cat_scores

[90, 79, 67, 45, 43, 78, 42, 89, 95, 82, 93, 79]

In [ ]:
#this is while using numpy-it generates the sum of each index per list
import numpy as np
end_term_scores=np.array([90,79,67,45])
mid_term_scores=np.array([43,78,42,89])
cat_scores=np.array([95,82,93,79])
end_term_scores+mid_term_scores+cat_scores

array([228, 239, 202, 213])

In [ ]:
import numpy as np
marks = np.random.randint(40,101,50) # Assign the result of the function call to marks
marks+5
new_marks=marks+5
print("Initial marks:" ,marks)
print("Changed marks: ",new_marks)
print("The mean of initial marks is: " ,np.mean(marks))
print("The mean of changed marks is:  ",np.mean(new_marks))

Initial marks: [ 57  63  49  43  40  88  99 100  97  61  56  71  45  42  86  89  63 100
  40  78  84  77  70  97  54  67  79  66  93  56  61  98  90  95  66  60
  98  50 100  89  45  89  54  66 100  82  45  59  72  49]
Changed marks:  [ 62  68  54  48  45  93 104 105 102  66  61  76  50  47  91  94  68 105
  45  83  89  82  75 102  59  72  84  71  98  61  66 103  95 100  71  65
 103  55 105  94  50  94  59  71 105  87  50  64  77  54]
The mean of initial marks is:  71.56
The mean of changed marks is:   76.56


In [ ]:
marks[(marks<50)]

array([49, 43, 40, 45, 42, 40, 45, 45, 49])

In [ ]:
marks[(marks<50)].size

9

In [ ]:
marks[(marks>80)]


array([ 88,  99, 100,  97,  86,  89, 100,  84,  97,  93,  98,  90,  95,
        98, 100,  89,  89, 100,  82])

In [ ]:
marks[(marks>80)].size

19

In [ ]:
marks[marks<=95]#for selecting a specific category

array([57, 63, 49, 43, 40, 88, 61, 56, 71, 45, 42, 86, 89, 63, 40, 78, 84,
       77, 70, 54, 67, 79, 66, 93, 56, 61, 90, 95, 66, 60, 50, 89, 45, 89,
       54, 66, 82, 45, 59, 72, 49])

For boolean masking in numpy and is (&), or is(|), not is(~)

In [ ]:
import numpy as np
scores=np.array([98,70,56,97,46])
scores[~(scores>95)&(scores>60)|(scores<50)]

array([70, 46])

In [ ]:
def adder(num):
  return num+5



In [ ]:
uadder=np.vectorize(adder) #np.vectorize converts our defined function "adder" into a universal function(ufunc) to "uadder"

In [ ]:
scores=np.array([90,45,67])#without looping, it adds 5 to all numbers in array
uadder(scores)

array([95, 50, 72])

In [ ]:
uadder2=np.frompyfunc(adder,1,1)#with this method of np.frompyfunc, the values returned are always objects
uadder2(scores)

array([95, 50, 72], dtype=object)

In [ ]:
def stat(num1,num2):
  return(num1+num2, (num1+num2)/2)

In [ ]:
ustat=np.frompyfunc(stat,2,2)
arr_1=np.array([1,2,3])
arr_2=np.array([2,3,4])
ustat(arr_1,arr_2)

(array([3, 5, 7], dtype=object), array([1.5, 2.5, 3.5], dtype=object))

Create a function(summary)that displays the mean,median,std,var,dtype,size,shape of an array and returns the corresponding grade

In [ ]:
import numpy as np

def grade(score):
    if score >= 70:
        return "A"
    elif score >= 60:
        return "B"
    elif score >= 50:
        return "C"
    elif score >= 40:
        return "D"
    else:
        return "E"

# Vectorize the grading function
grade_vector = np.vectorize(grade)

def summary(data):
    data = np.array(data)

    mean = np.mean(data)

    print("Mean:", mean)
    print("Median:", np.median(data))
    print("Standard Deviation:", np.std(data))
    print("Variance:", np.var(data))
    print("Data Type:", data.dtype)
    print("Size:", data.size)
    print("Shape:", data.shape)

    # Put the mean into an array so vectorize can process it
    return grade_vector(np.array([mean]))[0]

marks = [80, 75, 90, 60, 70]

print("Grade:", summary(marks))

Mean: 75.0
Median: 75.0
Standard Deviation: 10.0
Variance: 100.0
Data Type: int64
Size: 5
Shape: (5,)
Grade: A


#A retail store tracks daily sales revenue across a 30-day month. You need to analyze sales trends, find peak performance days, filter out slow days, and flag anomalous sales spikes (outliers).

array([4374, 2060, 2494, 2330, 2295, 4292, 2838, 3369, 1666, 2438, 1530,
       2682, 8500, 4371, 4119, 1330, 2885, 1969, 3591, 2715, 4053, 3633,
       2415, 2155, 3524, 9200, 1659, 1221, 3500, 1947])

In [ ]:
import numpy as np
sales_rev=np.array([4374, 2060, 2494, 2330, 2295, 4292, 2838, 3369, 1666, 2438, 1530,      #create a numpy array of the sales revenue array to enable to get statistical data
       2682, 8500, 4371, 4119, 1330, 2885, 1969, 3591, 2715, 4053, 3633,
       2415, 2155, 3524, 9200, 1659, 1221, 3500, 1947])
print("Mean sales: ", np.mean(sales_rev))
print("Median sales: ", np.median(sales_rev))
print("Highest sales revenue : ", np.max(sales_rev))
print("Peak performance days: ", np.argmax(sales_rev)+1) #we add one because argmax function starts counting positions from 0 and days in a month begin with 1
print("Slow days: ",sales_rev[sales_rev<2500]) #filtering out sales that are below 2500
sales_rev[(sales_rev>=2500)] #keeping sales that are above or equal to 2500
q1=np.percentile(sales_rev,25) #getting the 25th percentile
q3=np.percentile(sales_rev,75) #getting the 75th percentile
iqr=q3-q1#to see how they are spread in the middle
lower=q1-1.5*iqr#for giving some allowance  for lower values
upper=q3+1.5*iqr#for giving some allowance for higher values

outliers=sales_rev[(sales_rev<lower)|(sales_rev>upper)] #the values that are below the lower range and values that are above the upper range
print("Outliers: ",outliers)

print("Peak sales revenue : ", sales_rev[sales_rev>q3])
print("Peak sales days : ", np.where(sales_rev>q3)[0]+1) #we put the zero because np.where always gives a tuple therefore the zero instructs python to print the first index of the tuple whiuch is the array list then ads 1 to each value





Mean sales:  3171.8333333333335
Median sales:  2698.5
Highest sales revenue :  9200
Peak performance days:  26
Slow days:  [2060 2494 2330 2295 1666 2438 1530 1330 1969 2415 2155 1659 1221 1947]
Outliers:  [8500 9200]
Peak sales revenue :  [4374 4292 8500 4371 4119 4053 3633 9200]
Peak sales days :  [ 1  6 13 14 15 21 22 26]


In [ ]:
np.where(sales_rev>q3)[0]

array([ 0,  5, 12, 13, 14, 20, 21, 25])