<a href="https://colab.research.google.com/github/victoriairungu99-creator/CDAV-course/blob/main/Week_3_Day_12(Tuesday).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectorization

Allows you to generate a lot of output without looping as looping is time consuming and tiring with a huge dataset

In [ ]:
import numpy as np #include np.array so as to allow vectorization
scores=[45,89,76,67]
scores= np.array(scores)
scores+5

array([50, 94, 81, 72])

In [ ]:
#numpy can also be used to add different lists and give totals on each indexe(i.e, for each student)
#this one is for adding lists and it gives you the numbers in  total as they are but not added
end_term_scores=[90,79,67,45]
mid_term_scores=[43,78,42,89]
cat_scores=[95,82,93,79]
end_term_scores+mid_term_scores+cat_scores

[90, 79, 67, 45, 43, 78, 42, 89, 95, 82, 93, 79]

In [ ]:
#this is while using numpy-it generates the sum of each index per list
import numpy as np
end_term_scores=np.array([90,79,67,45])
mid_term_scores=np.array([43,78,42,89])
cat_scores=np.array([95,82,93,79])
end_term_scores+mid_term_scores+cat_scores

array([228, 239, 202, 213])

In [ ]:
import numpy as np
marks = np.random.randint(40,101,50) # Assign the result of the function call to marks
marks+5
new_marks=marks+5
print("Initial marks:" ,marks)
print("Changed marks: ",new_marks)
print("The mean of initial marks is: " ,np.mean(marks))
print("The mean of changed marks is:  ",np.mean(new_marks))

Initial marks: [ 57  63  49  43  40  88  99 100  97  61  56  71  45  42  86  89  63 100
  40  78  84  77  70  97  54  67  79  66  93  56  61  98  90  95  66  60
  98  50 100  89  45  89  54  66 100  82  45  59  72  49]
Changed marks:  [ 62  68  54  48  45  93 104 105 102  66  61  76  50  47  91  94  68 105
  45  83  89  82  75 102  59  72  84  71  98  61  66 103  95 100  71  65
 103  55 105  94  50  94  59  71 105  87  50  64  77  54]
The mean of initial marks is:  71.56
The mean of changed marks is:   76.56


In [ ]:
marks[(marks<50)]

array([49, 43, 40, 45, 42, 40, 45, 45, 49])

In [ ]:
marks[(marks<50)].size

9

In [ ]:
marks[(marks>80)]


array([ 88,  99, 100,  97,  86,  89, 100,  84,  97,  93,  98,  90,  95,
        98, 100,  89,  89, 100,  82])

In [ ]:
marks[(marks>80)].size

19

In [ ]:
marks[marks<=95]#for selecting a specific category

array([57, 63, 49, 43, 40, 88, 61, 56, 71, 45, 42, 86, 89, 63, 40, 78, 84,
       77, 70, 54, 67, 79, 66, 93, 56, 61, 90, 95, 66, 60, 50, 89, 45, 89,
       54, 66, 82, 45, 59, 72, 49])

For boolean masking in numpy and is (&), or is(|), not is(~)

In [ ]:
import numpy as np
scores=np.array([98,70,56,97,46])
scores[~(scores>95)&(scores>60)|(scores<50)]

array([70, 46])

In [ ]:
def adder(num):
  return num+5



In [ ]:
uadder=np.vectorize(adder) #np.vectorize converts our defined function "adder" into a universal function(ufunc) to "uadder"

In [ ]:
scores=np.array([90,45,67])#without looping, it adds 5 to all numbers in array
uadder(scores)

array([95, 50, 72])

In [ ]:
uadder2=np.frompyfunc(adder,1,1)#with this method of np.frompyfunc, the values returned are always objects
uadder2(scores)

array([95, 50, 72], dtype=object)

In [ ]:
def stat(num1,num2):
  return(num1+num2, (num1+num2)/2)

In [ ]:
ustat=np.frompyfunc(stat,2,2)
arr_1=np.array([1,2,3])
arr_2=np.array([2,3,4])
ustat(arr_1,arr_2)

(array([3, 5, 7], dtype=object), array([1.5, 2.5, 3.5], dtype=object))

Create a function(summary)that displays the mean,median,std,var,dtype,size,shape of an array and returns the corresponding grade

In [ ]:

def summary(num1):
  return
  if num1>80:
    print("Grade A")
  elif num1>70:
    print("Grade B")
  elif num1>60:
    print("Grade C")
  elif num1>50:
    print("Grade D")
  elif num1>40:
    print("Grade E")
  else:
    print("Grade F")