<a href="https://colab.research.google.com/github/victoriairungu99-creator/CDAV-course/blob/main/week_3_Day_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [4]:
#creating an array
#np.array has to be the prefix to your list because your data comes from numpy(np)
#this is a 0 dim array b ecause its only a scalar value(one item)
ages=np.array(10)
print(ages)

10


In [5]:
#1 dimensional array- array is created from a flat list(its not nested(list within a list))
ages=np.array([10,12,11,15])
print(ages)

[10 12 11 15]


In [7]:
#2 dimeniosnal array(list within a list)- the outer list and the inner list have same  number of opening and closing brackets
yob_age=np.array([[2000,26] ,[2002,24]])
print(yob_age)

[[2000   26]
 [2002   24]]


In [8]:
marks=[74,81,92,65,78]
marks_new=np.array(marks)
print(marks_new)

[74 81 92 65 78]


In [10]:
#.ndim gives you the  number of dimensions
marks_new.ndim

1

In [ ]:
#.shape gives you the number of element in each dimension
#.size gives you the total number of elements in your array
#.dtype gives you the data type

In [28]:
#Create a function that can take either a list or array and then gets the size, shape, data type and no.of dimensions
import numpy as np
def array_info(data):
  data=np.array(data)
  print("Number of dimensions: ",data.ndim)
  print("Shape: ",data.shape)
  print("Size: ",data.size)
  print("Data type: ",data.dtype)

my_list=([[18,16],[20,22]])
array_info(my_list)




Number of dimensions:  2
Shape:  (2, 2)
Size:  4
Data type:  int64


In [1]:
import numpy as np
a=np.arange(20)
print("a[15]=", a[15])
print("a[-8:17:1]=", a[-8:17:1])
print("a[10]=", a[10:])

a[15]= 15
a[-8:17:1]= [12 13 14 15 16]
a[10]= [10 11 12 13 14 15 16 17 18 19]


In [4]:
np.array([82,75,91,68,80])
print(1:4:1)

SyntaxError: invalid syntax (3515769439.py, line 2)

In [ ]:
import numpy as np
a=np.array([1,2], [3,4], [5,6])

In [5]:
import numpy as np
a=np.array([10,40,80,50,100])
print(a[a>50])

[ 80 100]


In [6]:
np.linspace(0,100,5)#the endpoint is not exclusive;it is included and the last number indicates how many exact numbers you want in your output

array([  0.,  25.,  50.,  75., 100.])

In [7]:
np.random.randint(0,100,10)#the last n umber specifies how many numbers of items you want in your output

array([39,  1, 41, 90,  5, 39, 24, 75, 45, 66])

In [15]:
import numpy as np
scores=[]
scores=np.random.randint(21,95,40)
print(scores)

[44 29 58 29 66 54 27 81 33 30 29 84 53 55 68 78 61 30 78 43 37 79 77 41
 68 45 62 67 82 40 66 48 72 84 48 73 77 76 39 29]


In [16]:
scores.size#size gives you the  number of items in an array

40